USE FilmingDB;
GO

-- Различные уровни изоляции

-- 1) (READ UNCOMMITTED)
/*
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION;
    SELECT * FROM Movie;
    WAITFOR DELAY '00:00:15';
    SELECT * FROM Movie;
COMMIT TRANSACTION;
GO
*/

-- 2) Завершённое чтение (READ COMMITTED)
/*
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
BEGIN TRANSACTION;
    SELECT * FROM Movie;
    WAITFOR DELAY '00:00:15';
    SELECT * FROM Movie;
COMMIT TRANSACTION;
GO
*/

-- 3) Воспроизводимое чтение (REPEATABLE READ)

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRANSACTION;
    SELECT * FROM Movie;
    WAITFOR DELAY '00:00:15';
    SELECT * FROM Movie;
COMMIT TRANSACTION;
GO


-- 4) Serializable
/*
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRANSACTION;
    SELECT * FROM Movie;
    WAITFOR DELAY '00:00:15';
    SELECT * FROM Movie;
COMMIT TRANSACTION;
GO
*/
